# Generated by Django 5.1.3 on 2024-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Adaugă un imagine mem după dispoziția ta')),
                ('theme', models.CharField(choices=[('programare', 'Programare'), ('it', 'IT')], max_length=50, verbose_name='Tematica')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('date', models.DateField(verbose_name='Data')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagine')),
                ('description', models.TextField(blank=True, verbose_name='Descriere (optional)')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
        ),
    ]
