# Generated by Django 5.1.3 on 2024-12-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_galleryimage_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
